# Generated by Django 6.0.2 on 2026-03-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('home_type', models.CharField(choices=[('Individual', 'Individual House'), ('Apartment', 'Apartment'), ('Villa', 'Villa')], max_length=50)),
                ('sqr_feet', models.IntegerField()),
                ('contact_no', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='materials/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LaborCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrician_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plumber_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mason_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('painter_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carpenter_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.homeproject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.homeproject')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.material')),
            ],
        ),
    ]
