# Generated by Django 6.0.2 on 2026-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='profession_category',
            field=models.CharField(choices=[('Masonry', 'Masonry (Cement, Sand, Bricks, Steel)'), ('Electrical', 'Electrical (Wires, Switches, Pipes)'), ('Plumbing', 'Plumbing (Pipes, Taps, Motors)'), ('Carpentry', 'Carpentry (Wood, Doors, Locks)'), ('Painting', 'Painting (Paint, Primer, Brushes)')], default='Masonry', max_length=50),
        ),
    ]
