# Generated by Django 6.0.2 on 2026-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_homeproject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproject',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
